{"variants":[{"paths":["\/documentation\/connectsdk\/features"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/features"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/Features","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This section presents all the features available in "},{"type":"strong","inlineContent":[{"type":"text","text":"Insight Mobile"}]},{"type":"text","text":" iOS and explains how to integrate and use them within your system."}],"kind":"article","metadata":{"modules":[{"name":"ConnectSDK"}],"role":"collectionGroup","title":"Features"},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"topicSections":[{"title":"Worker Feedback","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/worker-feedback"]}],"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/worker-feedback":{"role":"article","title":"Worker Feedback","abstract":[{"type":"text","text":"Trigger feedback to the scanner"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/worker-feedback","kind":"article","type":"topic","url":"\/documentation\/connectsdk\/worker-feedback"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Worker Feedback","identifiers":["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/worker-feedback"]}]},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}