{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"Worker Feedback"}]},{"type":"text","text":" feature enables you to send messages to the connected devices in order to play specific feedback sequences. Use it to trigger your scanner’s feedback profiles asynchronously to notify workers about an event to enhance their workflow and help with daily tasks completion."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Worker Feedback commands, like all commands that trigger an action on a scanner, are queued in the "},{"type":"codeVoice","code":"ConnectSDK"},{"type":"text","text":" by default. To learn more, see "},{"type":"reference","isActive":true,"identifier":"https:\/\/docs.proglove.com\/en\/queueing-behavior.html"},{"type":"text","text":"."}]},{"anchor":"Trigger-feedback-using-iOS-SDK","level":2,"type":"heading","text":"Trigger feedback using iOS SDK"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To trigger a feedback a connected scanner, "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager"},{"type":"text","text":" provides the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackManager"},{"type":"text","text":" property with the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackManager\/playFeedbackSequence(withFeedbackCommand:completionHandler:)"},{"type":"text","text":" method."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The method accepts a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand"},{"type":"text","text":" with "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest"},{"type":"text","text":" data containing the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback"},{"type":"text","text":" ID. If the request fails, an Error object will be returned via the completion handler block."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can check the vailable feedback IDs "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback"},{"type":"text","text":"."}]},{"anchor":"Swift","level":4,"type":"heading","text":"Swift"},{"type":"codeListing","syntax":"swift","code":["let feedbackManager = central.feedbackManager","","let feedbackRequest = PGFeedbackRequest(feedback: .success)","let command = PGCommand(feedbackRequest: feedbackRequest)","","feedbackManager?.playFeedbackSequence(withFeedbackCommand: command, completionHandler: { (error) in","    \/\/handle response","})"]},{"anchor":"Objective-C","level":4,"type":"heading","text":"Objective-C"},{"type":"codeListing","syntax":"objc","code":["PGFeedbackManager *feedbackManager = central.feedbackManager;","","PGFeedbackRequest *feedbackRequest = [[PGFeedbackRequest alloc] initWithFeedback:PGPredefinedFeedbackSuccess];","PGCommand *command = [[PGCommand alloc] initWithFeedbackRequest:feedbackRequest];","","[feedbackManager playFeedbackSequenceWithFeedbackCommand:command completionHandler:^(NSError * _Nullable error) {","    \/\/handle response","}];"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/connectsdk\/worker-feedback"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/connectsdk\/worker-feedback"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/worker-feedback","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Trigger feedback to the scanner"}],"kind":"article","metadata":{"roleHeading":"Article","title":"Worker Feedback","role":"article","modules":[{"name":"ConnectSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK"]]},"references":{"doc://com.proglove.Mark2SDK/documentation/ConnectSDK":{"role":"collection","title":"ConnectSDK","abstract":[{"type":"text","text":"The "},{"type":"strong","inlineContent":[{"type":"text","text":"ProGlove ConnectSDK"}]},{"type":"text","text":" is a software development kit that enables integration between your iOS apps and the ProGlove system."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK","kind":"symbol","type":"topic","url":"\/documentation\/connectsdk"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGPredefinedFeedback":{"role":"symbol","title":"PGPredefinedFeedback","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGPredefinedFeedback"}],"abstract":[{"type":"text","text":"Feedback enum"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGPredefinedFeedback","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGPredefinedFeedback"}],"url":"\/documentation\/connectsdk\/pgpredefinedfeedback"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCentralManager":{"role":"symbol","title":"PGCentralManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCentralManager"}],"abstract":[{"type":"text","text":"PGCentralManager"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCentralManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGCentralManager"}],"url":"\/documentation\/connectsdk\/pgcentralmanager"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackRequest":{"role":"symbol","title":"PGFeedbackRequest","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGFeedbackRequest"}],"abstract":[{"type":"text","text":"Model representing PGFeedback Request"}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGFeedbackRequest"}],"url":"\/documentation\/connectsdk\/pgfeedbackrequest"},"https://docs.proglove.com/en/queueing-behavior.html":{"title":"Queueing behavior","titleInlineContent":[{"type":"text","text":"Queueing behavior"}],"type":"link","identifier":"https:\/\/docs.proglove.com\/en\/queueing-behavior.html","url":"https:\/\/docs.proglove.com\/en\/queueing-behavior.html"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGCommand":{"role":"symbol","title":"PGCommand","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGCommand"}],"abstract":[{"type":"text","text":"A PGCommand is used to send a command to a connected device through Connect SDK."},{"type":"text","text":" "},{"type":"text","text":"The maximum number of PGCommands that can be sent to a device at a time is 1."},{"type":"text","text":" "},{"type":"text","text":"The maximum PGCommands that can be queued for sending is 5."},{"type":"text","text":" "},{"type":"text","text":"If PGCommand is requested and queue reached the limit, PGCommand will be droped and failed."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGCommand","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGCommand"}],"url":"\/documentation\/connectsdk\/pgcommand"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackManager":{"role":"symbol","title":"PGFeedbackManager","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PGFeedbackManager"}],"abstract":[{"type":"text","text":"Protocol contains all the feedback related methods."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PGFeedbackManager"}],"url":"\/documentation\/connectsdk\/pgfeedbackmanager"},"doc://com.proglove.Mark2SDK/documentation/ConnectSDK/PGFeedbackManager/playFeedbackSequence(withFeedbackCommand:completionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"playFeedbackSequenceWithFeedbackCommand:completionHandler:"}],"role":"symbol","title":"playFeedbackSequence(withFeedbackCommand:completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playFeedbackSequence"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withFeedbackCommand"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PGCommand","preciseIdentifier":"c:@M@ConnectSDK@objc(cs)PGCommand"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Plays sequence on a connected scanner based on a provided id."}],"identifier":"doc:\/\/com.proglove.Mark2SDK\/documentation\/ConnectSDK\/PGFeedbackManager\/playFeedbackSequence(withFeedbackCommand:completionHandler:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/connectsdk\/pgfeedbackmanager\/playfeedbacksequence(withfeedbackcommand:completionhandler:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback\/title","value":"PGPredefinedFeedback"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGPredefinedFeedback\/fragments","value":[{"kind":"identifier","text":"PGPredefinedFeedback"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/title","value":"PGCentralManager"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCentralManager\/fragments","value":[{"kind":"identifier","text":"PGCentralManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackRequest\/title","value":"PGFeedbackRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackRequest\/fragments","value":[{"kind":"identifier","text":"PGFeedbackRequest"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/title","value":"PGCommand"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGCommand\/fragments","value":[{"kind":"identifier","text":"PGCommand"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackManager\/title","value":"PGFeedbackManager"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackManager\/fragments","value":[{"kind":"identifier","text":"PGFeedbackManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackManager~1playFeedbackSequence(withFeedbackCommand:completionHandler:)\/title","value":"playFeedbackSequenceWithFeedbackCommand:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.proglove.Mark2SDK~1documentation~1ConnectSDK~1PGFeedbackManager~1playFeedbackSequence(withFeedbackCommand:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"playFeedbackSequenceWithFeedbackCommand:completionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}